### ISSUE TITLE
Under Unix folder permissions section, there is a type-O

### ISSUE THREAD

**Issue by rbaetz** [NetAppDocs/bluexp-classification#100]
### Page URL

https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html

### Page title

Install BlueXP classification on a host that has internet access

### Summary

Under Unix folder permissions section, it is supposed to be "/usr/lib/systemd/system" not "/user/lib/systemd/system"
There is no /user directory in unix machines.

<img width="680" alt="Screenshot 2024-01-19 at 6 42 31 PM" src="https://github.com/NetAppDocs/bluexp-classification/assets/95367425/fe36d1d0-f0bc-4310-ab10-7454c621961f">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by rbaetz** [comment]
![image](https://github.com/NetAppDocs/bluexp-classification/assets/95367425/7cd3730d-2923-4f20-970d-bb4919852f57)

**Comment by rbaetz** [comment]
Thanks for the follow up Tom.

FYI, the original email got tagged by the O365 Junk filter.


Rob Baetz
Solution Innovation Architect
Strategy Innovation Acceleration Team

NetApp
248.219.4195 Mobile Phone
***@***.******@***.***>

[NetApp logo]<https://www.netapp.com/>

[NetApp TV link]<https://www.netapp.tv/>[NetApp on Facebook]<https://www.facebook.com/NetApp>[NetApp on Instagram]<https://www.instagram.com/netapp/>[NetApp on YouTube]<https://www.youtube.com/netapp>[NetApp on LinkedIn]<https://www.linkedin.com/company/netapp/>[NetApp on X]<https://twitter.com/NetApp>[NetApp on Discord]<https://netappdiscord.com/>



From: Tom Onacki ***@***.***>
Date: Monday, January 22, 2024 at 8:36 AM
To: NetAppDocs/bluexp-classification ***@***.***>
Cc: Baetz, Robert ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/bluexp-classification] Under Unix folder permissions section, there is a type-O (Issue #100)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

EXTERNAL EMAIL - USE CAUTION when clicking links or attachments



Hi rbaetz<https://github.com/rbaetz>, Thanks for letting me know. I'll update this page shortly and let you know.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Rob,  I have made this change in the docs.  Thanks again for letting us know.

Tom
