### ISSUE TITLE
Please at a section under "Prepare the Linux host system" for NTP time sync

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-classification#102]
### Page URL

https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html

### Page title

Install BlueXP classification on a host that has internet access

### Summary

Hi Ben,

    We ran into an error "Unable to load Data Sense, Authorization error" during an implementation of Data Sense.  The issue is caused due to BlueXP and Data Sense VM times are not synced.  This issue has been seen at other customers also.  Please add a section referencing that NTP will need to be enabled and the BlueXP connector VM and Data Sense VM times must be synced.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi David,  Thanks for bringing this to our attention.  I will add this information into the docs shortly and let you know when it is live.  This is great information to add.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi David,  Would a user need to configure NTP for the connector when initially setting up the connector system?  We're thinking we might want to add info about enabling NTP in the connector docs too if the user is planning to also set up BlueXP classification.

**Comment by virtualhawk** [comment]
Hi Tom,

               Apologies for the delay.  I completely agree with adding it to the Connector docs also as both VM's need to be in time sync or it causes the UI issues.

Thanks,

David Hawkins
Professional Service Consultant
Global Services Solutions Center

NetApp
330.892.7057 Direct Phone
***@***.******@***.***>

[A logo with a white square on it    Description automatically generated with medium confidence]

[A black circle with white letters    Description automatically generated]   [A black and white logo    Description automatically generated]    [A black and white logo    Description automatically generated]    [A black circle with a white play button    Description automatically generated]    [A black circle with white letters in it    Description automatically generated]    [A black circle with white x in it    Description automatically generated]    [A black circle with white logo    Description automatically generated]

"We're committed to providing our customers with the best products and services. Scan the QR code or click on this link<https://listening.netapp.com/jfe/form/SV_3n6lnfKz33d6feC> to provide your feedback. All responses will be anonymous and kept confidential.  Thank you!"

**Comment by netapp-tonacki** [comment]
Thanks David.  We've updated the BlueXP classification docs and the Connector setup docs (Ben did this) with this requirement for enabling NTP.  We made changes in a few locations - here are 2 examples:

- https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-4-prepare-networking-for-the-connector
- https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#prepare-the-linux-host-system

Thanks again for bringing this to our attention.

Tom

**Comment by virtualhawk** [comment]
Awesome!  Thank you both as always!  The quick turnaround on updating the docs is greatly appreciated!

Thanks,

David Hawkins
Professional Service Consultant
Global Services Solutions Center

NetApp
330.892.7057 Direct Phone
***@***.******@***.***>

[A logo with a white square on it    Description automatically generated with medium confidence]

[A black circle with white letters    Description automatically generated]   [A black and white logo    Description automatically generated]    [A black and white logo    Description automatically generated]    [A black circle with a white play button    Description automatically generated]    [A black circle with white letters in it    Description automatically generated]    [A black circle with white x in it    Description automatically generated]    [A black circle with white logo    Description automatically generated]

"We're committed to providing our customers with the best products and services. Scan the QR code or click on this link<https://listening.netapp.com/jfe/form/SV_3n6lnfKz33d6feC> to provide your feedback. All responses will be anonymous and kept confidential.  Thank you!"
