### ISSUE TITLE
Running sudo yum update -y upgrades RHEL to unsupported version

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-classification#128]
### Page URL

https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html

### Page title

Install BlueXP classification on a host that has internet access

### Summary

The following paragraph needs to be changed.  If you run "sudo yum update -y" it will currently upgrade the system to RHEL 9.4 which is not supported with the software.

Podman version 4 or greater. To install Podman, update your system packages (sudo yum update -y), and then install Podman (sudo yum install netavark -y).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
@jasonfiset - thank you for your comment. I will bring it to the BlueXP classification team for confirmation and resolution. I'll get back to you with their response. Meanwhile, if you see anything else, please don't hesitate to let us know. Thank you!

**Comment by amgrissino** [comment]
@jasonfiset  - I have pinged the PM again.

**Comment by amgrissino** [comment]
In the 3 deploy topics, we'll change the following. 

FROM this:
Podman version 4 or greater. To install Podman, update your system packages (sudo yum update -y), and then install Podman (sudo yum install netavark -y).

TO this:
Podman version 4 or greater. Install Podman (sudo yum install podman netavark -y).

**Comment by amgrissino** [comment]
3 topics are updated. Closing this. Thank you @jasonfiset !
