### ISSUE TITLE
Port requirements when using Restricted Mode connector

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-classification#129]
### Page URL

https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html

### Page title

Check that your Linux host is ready to install BlueXP classification

### Summary

In the section "Verify that all required ports are enabled" it appears to be missing port 9060 and 9061 as outlined in the BlueXP connector installation: https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-azure.html and https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-aws.html for deployment in government regions or restricted mode.  Installation fails if these ports are blocked by a firewall between the scanner and the connector.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Hello, @jasonfiset. I've sent your comment to the BlueXP classification team for confirmation. Thank you for the catch!

**Comment by amgrissino** [comment]
Per the BlueXP classification team; Ports 9060, 9061 are never used now in BlueXP classification. I will send this comment to the BlueXP set up writer. Closing this for BlueXP classification.
