### ISSUE TITLE
StorageGRID is now a supported data source in v1.35

### ISSUE THREAD

**Issue by sbyosh** [NetAppDocs/bluexp-classification#137]
### Page URL

https://docs.netapp.com/us-en/bluexp-classification/reference-free-paid.html

### Page title

BlueXP classification deprecated features

### Summary

The release notes say that StorageGRID is back to being a supported data source, so the deprecated features table needs to be updated: https://docs.netapp.com/us-en/bluexp-classification/whats-new.html#2-september-2024-version-1-35

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Closing this.
