### ISSUE TITLE
Feedback on Scanning object storage that uses S3 protocol

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/bluexp-classification#57]
Page: [Scanning object storage that uses S3 protocol](https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-object-storage.html)

Received feedback via doccomments:
I was alerted to this very strange sentence in the Data Sense/Governance docs: https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-object-storage.html#reviewing-object-storage-requirements

•	Support for Azure Blob requires that you use the [MinIO service](https://min.io/).

It doesn’t specify much about MinIO and the link goes to the Min.io website, not to any usage of the product… I was wondering if we could get more detail?

Also, noting that incorrect use of the MinIO (or rather, Apache) license has been in the news recently...

**Comment by netapp-tonacki** [comment]
Thanks for entering this Chanda.    I have sent a request to the Dev team and PM to provide instructions for setting up MinIO to scan Azure Blog storage.

**Comment by netapp-tonacki** [comment]
Update:  I resent an email on the 12th about this.  And sent email again today to the CDS team to get an answer.

**Comment by netapp-tonacki** [comment]
Update: The Dev team has an action to provide me with the instruction for setting up MinIO to scan Azure Blog storage.  Still waiting for this information.

**Comment by netapp-tonacki** [comment]
Hi,  I just heard from the Product Manager today that we don't support scanning Azure Blob data using an integration with MinIO.  So I have removed these references from the published docs and asked that they update the posts on Teams that had initially posed this question.  Let me know if I can Close this.

Thanks, Tom
