### ISSUE TITLE
Update BlueXP Serial number information || How and Where to Obtain 

### ISSUE THREAD

**Issue by chhabrag87** [NetAppDocs/bluexp-classification#74]
### Page URL

https://docs.netapp.com/us-en/bluexp-classification/task-licensing-datasense.html

### Page title

Set up licensing for BlueXP classification

### Summary

Hi, In recent many cases with customer we observed this as an open ended question, where to find the BlueXP serial number to generate the BlueXP Classification service license. If document can show screengrab and one liner that obtain the BlueXP serial number from Sales Order and customer can ask account team to provide that information. I feel that's an extra dependency and gap to generate the license file. Along with customer even PS team also struggle to find this information. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@chhabrag87,

Thank you for submitting this feedback. A member of our team will take a look at your feedback and respond soon.

Thanks again,
Ben

**Comment by netapp-tonacki** [comment]
Hi Gorav,  Thanks again for your feedback.  We have similar wording in some of our other services docs, so I'll make similar changes to them in case those users are also having problems.  

What I did was add a new heading before the steps to let the user know that they'll need to get this information before they start.  We had an item about locating the BlueXP Account ID within the steps, so I added that to this section as well.  It looks like this:

**Before you begin**
You’ll need to have the following information before you start:

- BlueXP classification serial number
Locate this number from your Sales Order, or contact the account team for this information.

- BlueXP Account ID
You can find your BlueXP Account ID by selecting the Account drop-down from the top of BlueXP, and then clicking Manage Account next to your account. Your Account ID is in the Overview tab.

You can see the real info here: https://docs.netapp.com/us-en/bluexp-classification/task-licensing-datasense.html#obtain-your-bluexp-classification-license-file 

Let me know what you think.  And if you can send me a screenshot of a Sales Order with this info highlighted, I'll see if I can get this added as well.

Tom

**Comment by netapp-tonacki** [comment]
Hi Gorav,  I saw your email response with a screenshot of the Sales Order.  To me it looks like the Serial Number for the license is pretty straight-forward once the user views the Sales Order.  Now that the docs mention checking the Sales Order, do you think it is necessary to show a screenshot?

Let me know.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Gorav,  I'm going to close this out now.  Thanks for your feedback.

Thanks, Tom
