### ISSUE TITLE
What really happens when turning scanning "off" for a repository.

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-classification#76]
### Page URL

https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html

### Page title

Changing the scan settings for your repositories

### Summary

I feel that this paragraph under "Pausing and resuming scanning for a repository" should be moved up the page and perhaps re-worded:

You can "pause" scanning on a repository if you want to temporarily stop scanning certain content. This is not the same as turning scanning "off". When scanning is turned off, all the indexing and information about that volume is removed from the system, and charging for scanning the data is stopped. Pausing scanning means that BlueXP classification won’t perform any future scans for changes or additions to the repository, but that all the current results will still be displayed in the system. Pausing scanning does not stop charging to scan the data because the data still exists.

I was looking for a way to reset their scanner database - basically rescan their data source from scratch and this wan't obvious to find it in the section labelled "Pausing and resuming scanning..." when it really should have been something pointed out in the section above where it talks about Map, Map & Classify or Off settings.  I feel it would have fit better in the "Changing the type of scanning for a repository" by describing what the "Off" setting does and then in the Pause section, just focus on what happens when you Pause a repo.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi [jasonfiset](https://github.com/jasonfiset), Thanks for your feedback,  I see your point and I agree that the information about stopping scanning should be in the other section.  After seeing what your user wanted to do - discard all scanned information and start again - I think I'll add a section for "Stopping scanning for a repository" since "stopping" is really different than "changing the type" of scanning for a repository.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
I have added a [new section for stopping scanning](https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#stopping-scanning-for-a-repository) and I revised the other 2 topics for Pausing and for Changing scan settings.  Let me know what you think.

Thanks, Tom

**Comment by jasonfiset** [comment]
That looks good.  Breaking it out into its own section makes it easier to find more quickly than before.  Thanks Tom.

**Comment by netapp-tonacki** [comment]
Thanks again for bring this up Jason.
