### ISSUE TITLE
Change in wording under "Reviewing SharePoint requirements"

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-classification#87]
### Page URL

https://docs.netapp.com/us-en/bluexp-classification/task-scanning-sharepoint.html

### Page title

Scanning SharePoint accounts

### Summary

Above the first bullet in this URL,  "You must have the Admin user login credentials for the SharePoint account that provides read access to all SharePoint sites." which is incorrect.

SharePoint admin doesn't always give you access to all SharePoint sites and OneDrive folders.  It is described here under "Site Management" in this Microsoft link: https://learn.microsoft.com/en-us/sharepoint/sharepoint-admin-role.

I am not aware of an Microsoft pre-built Admin role that has access to all sites.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi David,  Thanks for your question.  I forwarded your question to the PMs to take a look along with your related item I saw in Teams.  So hopefully they'll have an answer or can have someone on the Dev team clarify what is needed, or the best way to do this.

Thanks, Tom

**Comment by virtualhawk** [comment]
Hi Tom,

               Thank you so much!

Thanks,

David Hawkins
Professional Services Consultant
Global Services Solutions Center

NetApp
3308927057 - <tel:+19194768564>  Direct Phone
***@***.******@***.***>

Upcoming Out of the office: None

**Comment by netapp-tonacki** [comment]
Hi David,  I saw that someone on Teams responded to your question and it seemed to me like they were saying mostly what's in the docs already.  I could be wrong...  Were you able to get this working for your user?  Do you feel I still need to add additional information in the docs for this issue?

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi David,  Please let me know what you think about my last comment. Unless the Dev team designs some other access method for  SharePoint, what's in the docs looks like what we offer today.  I plan to close this doc issue unless you disagree.

Thanks, Tom
