### ISSUE TITLE
update CSV row numbers to match GUI. 

### ISSUE THREAD

**Issue by stubb1986** [NetAppDocs/bluexp-classification#93]
### Page URL

https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html

### Page title

Investigate the data stored in your organization

### Summary

Update the below to match what the GUI says which is 10,000 rows instead of 5,000 rows.

_Data Investigation Report
The Data Investigation Report is a download of the filtered contents of the Data Investigation page.

You can save the report in two different formats:

As a .CSV file to the local machine; which can include up to **5,000** rows of data._

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi @stubb1986, Thanks for letting me know.  I will update the docs to reflect the update to 10,000 rows in the CSV report.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
I have updated the doc page to reflect 10,000 rows max for CSV file export.  Thanks again @stubb1986
